CREATE TABLE dtFolders (
    folder_id INTEGER,
    foldername TEXT,
    folderaddress1 TEXT,
    folderaddress2 TEXT,
    foldercity TEXT,
    folderstatecode TEXT,
    folderzipcode TEXT,
    shippingaddress1 TEXT,
    shippingaddress2 TEXT,
    shippingcity TEXT,
    shippingaddressstatecode TEXT,
    shippingaddresszipcode TEXT,
    folder_expiration_date TEXT,
    folder_campaign TEXT,
    folder_template TEXT,
    userid INTEGER,
    clientcompanycode TEXT,
    client_company_name TEXT,
    programname TEXT,
    client_program_name TEXT,
    delivered_date TEXT,
    replaced_count INTEGER,
    battery_quantity INTEGER
);